language: java

env:
 - CODACY_PROJECT_TOKEN=bd8e7040a9184acd9b9b73b90fbaa122

jdk:
  - oraclejdk8          // tells Travis to use Java 8

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - cd ganttproject-builder; chmod +x gradlew



script:
- "./gradlew clean build test"
- "./gradlew jacocoTestReport"

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml